# NTDL API
@baseUrl = http://localhost:8000/api/v1/tasks


### POST THE TASK LIST
POST {{baseUrl}}
Content-Type: application/json

{
    "id":4,
    "task":"coding",
    "hr":"40",
    "type":"entry"
}
### GET THE TASK LIST
GET {{baseUrl}}

### UPDATE THE TASK LIST
PATCH  {{baseUrl}}
Content-Type: application/json


{
    "id":2,
    "task":"coding",
    "hr":"40",
    "type":"bad"

}

### DELETE THE TASK LIST
DELETE  {{baseUrl}}/2
