# NTDL API
@baseUrl = http://localhost:8000/api/v1/tasks


### POST THE TASK LIST
POST {{baseUrl}}
Content-Type: application/json

{
    "task":"coding",
    "hr":"40"
}
### GET THE TASK LIST
GET {{baseUrl}}

### UPDATE THE TASK LIST
PUT {{baseUrl}}

### DELETE THE TASK LIST
DELETE  {{baseUrl}}
